# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2546c43e25edc4472c331f077f7963cc150f93bcc054a21baa03e74304206a3ba49c660bd9959fc959d4768f29f2412df2ea3fcc5d6cc2c44997c1d04de14aa

test:
  secret_key_base: ce68b86f9578df4323aea3c146b46a5d1449a40909073020ac05a071af88ffc7b5e7b3fd78ee9dbdfc351554d5b2753bc0c9485eb1def073e30898c9a596cc0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
